import { INR_BALANCES_TYPE, ORDER_BOOK_TYPE, STOCK_BALANCES_TYPE } from "../types/global";

export let INR_BALANCES: INR_BALANCES_TYPE = {}
export let STOCK_BALANCES: STOCK_BALANCES_TYPE = {}
export let ORDERBOOK: ORDER_BOOK_TYPE = {}