apiVersion: apps/v1
kind: Deployment
metadata:
  name: probo-engine
  labels:
    app: probo-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: probo-engine
  template:
    metadata:
      labels:
        app: probo-engine
    spec:
      containers:
        - name: probo-engine
          image: rithik933/probo-engine:v1
          ports:
            - containerPort: 3001
