apiVersion: apps/v1
kind: Deployment
metadata:
  name: probo-api
  labels:
    app: probo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: probo-api
  template:
    metadata:
      labels:
        app: probo-api
    spec:
      containers:
        - name: probo-api
          image: rithik933/probo-api:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
