apiVersion: v1
kind: Service
metadata:
  name: probo-api
spec:
  type: LoadBalancer  # Exposes service to external traffic
  selector:
    app: probo-api
  ports:
    - protocol: TCP
      port: 80       # External Port (Clients connect here)
      targetPort: 3000  # Internal Port in the container
