apiVersion: apps/v1
kind: Deployment
metadata:
  name: probo-ws
  labels:
    app: probo-ws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: probo-ws
  template:
    metadata:
      labels:
        app: probo-ws
    spec:
      containers:
        - name: probo-ws
          image: rithik933/probo-ws:v1
          ports:
            - containerPort: 8080
